### ISSUE TITLE
Support Poetry 1.5 and 1.6

### ISSUE THREAD

**Issue by emersonfoni** [paketo-buildpacks/poetry#265] opened 2023-10-13 13:14 UTC
## Describe the Enhancement
The current buildpack only supports Poetry 1.4.2, which is now five months old. Poetry has improved over the last 5 months, as you can see from their [release notes](https://github.com/python-poetry/poetry/releases).

## Possible Solution
Support 1.5 and 1.6. 

## Motivation
Modern `pyproject.toml` files are incompatible with the buildpack, e.g. ones using `priority` attributes in `pyproject.toml` for `[[tool.poetry.source]]`.

**Comment by robdimsdale** [comment] 2023-10-13 15:17
Duplicate of #255. The next release of poetry will support 1.5 and 1.6

**Closed by robdimsdale** 2023-10-13 15:17 UTC

**Comment by emersonfoni** [comment] 2023-10-13 17:07
Oops, sorry for the dupe!
